# Generated by Django 5.1 on 2024-08-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_spotifyargentinatoppodcasts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregatedarts',
            name='podcast_artwork',
        ),
        migrations.RemoveField(
            model_name='aggregatedarts',
            name='podcast_link',
        ),
        migrations.RemoveField(
            model_name='aggregatedarts',
            name='podcast_name',
        ),
        migrations.AddField(
            model_name='aggregatedarts',
            name='category',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
