# Generated by Django 5.1 on 2024-08-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_aggregatedarts_podcast_artwork_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedarts',
            name='podcast_artwork',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='aggregatedarts',
            name='podcast_creator',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='aggregatedarts',
            name='podcast_link',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='aggregatedarts',
            name='podcast_name',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
