# Generated by Django 5.1 on 2024-08-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aggregatedarts_podcast_artwork_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('podcast_name', models.CharField(default='null', max_length=255)),
                ('podcast_link', models.CharField(default='null', max_length=255)),
                ('podcast_artwork', models.CharField(default='null', max_length=255)),
                ('podcast_creator', models.CharField(default='null', max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aggregated_business',
            },
        ),
        migrations.CreateModel(
            name='AggregatedComedy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('podcast_name', models.CharField(default='null', max_length=255)),
                ('podcast_link', models.CharField(default='null', max_length=255)),
                ('podcast_artwork', models.CharField(default='null', max_length=255)),
                ('podcast_creator', models.CharField(default='null', max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aggregated_comedy',
            },
        ),
        migrations.CreateModel(
            name='AggregatedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('podcast_name', models.CharField(default='null', max_length=255)),
                ('podcast_link', models.CharField(default='null', max_length=255)),
                ('podcast_artwork', models.CharField(default='null', max_length=255)),
                ('podcast_creator', models.CharField(default='null', max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aggregated_history',
            },
        ),
        migrations.CreateModel(
            name='AggregatedLeisure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('podcast_name', models.CharField(default='null', max_length=255)),
                ('podcast_link', models.CharField(default='null', max_length=255)),
                ('podcast_artwork', models.CharField(default='null', max_length=255)),
                ('podcast_creator', models.CharField(default='null', max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aggregated_leisure',
            },
        ),
        migrations.CreateModel(
            name='AggregatedPolitics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('podcast_name', models.CharField(default='null', max_length=255)),
                ('podcast_link', models.CharField(default='null', max_length=255)),
                ('podcast_artwork', models.CharField(default='null', max_length=255)),
                ('podcast_creator', models.CharField(default='null', max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aggregated_politics',
            },
        ),
        migrations.CreateModel(
            name='AggregatedReligion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('podcast_name', models.CharField(default='null', max_length=255)),
                ('podcast_link', models.CharField(default='null', max_length=255)),
                ('podcast_artwork', models.CharField(default='null', max_length=255)),
                ('podcast_creator', models.CharField(default='null', max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aggregated_religion',
            },
        ),
        migrations.CreateModel(
            name='AggregatedScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('podcast_name', models.CharField(default='null', max_length=255)),
                ('podcast_link', models.CharField(default='null', max_length=255)),
                ('podcast_artwork', models.CharField(default='null', max_length=255)),
                ('podcast_creator', models.CharField(default='null', max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aggregated_science',
            },
        ),
        migrations.CreateModel(
            name='AggregatedSports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('podcast_name', models.CharField(default='null', max_length=255)),
                ('podcast_link', models.CharField(default='null', max_length=255)),
                ('podcast_artwork', models.CharField(default='null', max_length=255)),
                ('podcast_creator', models.CharField(default='null', max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aggregated_sports',
            },
        ),
    ]
